### ISSUE TITLE
Customize toolbar to remove items

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/ji-wysiwyg-editor#5]
Should be able to remove items we aren't using - e.g. insert image, link, etc.

**Comment by jpuri** [comment]
Hey @dakom : can you plz list which all items are required.

**Comment by jpuri** [comment]
Done here: https://github.com/jewish-interactive/ji-wysiwyg-editor/commit/4faaef9120b1d0ea3e07a37af999e2cddec04f3f
