### ISSUE TITLE
Hebrew fonts to include

### ISSUE THREAD

**Issue by corinnewo** [jewish-interactive/ji-wysiwyg-editor#6]
Hebrew Google Fonts:
https://fonts.google.com/specimen/Assistant/
https://fonts.google.com/specimen/Varela+Round/
https://fonts.google.com/specimen/David+Libre/
https://fonts.google.com/specimen/Frank+Ruhl+Libre/

Related to  #3

**Comment by dakom** [comment]
Note - I've assigned this to me since they get preloaded in the consuming app and from the perspective of this editor become just font names like any other

**Comment by dakom** [comment]
Though on second thought we might want to include this in the Demo (i.e. it's also related to #2)
