### ISSUE TITLE
Include Virtual Hebrew Keyboard

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/ji-wysiwyg-editor#8]
Ideally this would actually be via some extensible plugin system - that way everyone using the core wysiwyg editor can add their own virtual keyboards if they want... and we could also more easily support things like Rashi Script, etc.

Of course this breaks down into many sub-issues - but I'm not aware of all those. @jpuri feel free to edit this as you see fit! Maybe checklist, or new issues... whatever floats your boat :)

**Comment by jpuri** [comment]
Feature added here: https://jewish-interactive.github.io/ji-wysiwyg-editor/
