### ISSUE TITLE
Style rules for Virtual Keyboard

### ISSUE THREAD

**Issue by dakom** [jewish-interactive/ji-wysiwyg-editor#9]
The end goal we need for the Demo/Example is to mirror the previous product: https://jewish-interactive.github.io/draft-canvas/

However, now that we're starting with a clean slate - perhaps we can define these rules so it's configurable?

@jpuri - please let us know what the complications might be for making it extensible... for sure the core need is just to match the style of the previous editor w/ the virtual keyboard, so if it's a big hassle to make it more configurable, we can postpone that for now

**Comment by jpuri** [comment]
@dakom : yes making this configurable is hard in available time frame.

**Comment by dakom** [comment]
@corinnewo - if you want to open this for discussion let us know.

Closing for now
